### ISSUE TITLE
A request hes failed.

### ISSUE THREAD

**Issue by KittenRaee** [Yesterday17/ZenScript#30]
I've installed Extension, Probe mod, added folder and whenever I try to write anything in a script, there's an error showing up:
`[Error - 18:42:52] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'tokens' of undefined
  Code: -32603 
[Error - 18:42:52] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'tokens' of undefined
  Code: -32603 
[Error - 18:42:52] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'tokens' of undefined
  Code: -32603 
[Error - 18:42:52] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'tokens' of undefined
  Code: -32603 
[Error - 18:42:52] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'tokens' of undefined
  Code: -32603 
[Error - 18:42:53] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'tokens' of undefined
  Code: -32603 
`

**Comment by Yesterday17** [comment]
hmm... That's strange. I cannot reproduce it.

**Comment by copygirl** [comment]
I have a similar issue. When I create an empty `.zs` file or open one, I get the following:
```
(node:18684) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at Function.<anonymous> (/home/copygirl/.vscode-oss/extensions/yesterday17.zenscript-0.2.4/out/server/services/zsDocumentContentChange.js:37:64)
    at Generator.next (<anonymous>)
    at fulfilled (/home/copygirl/.vscode-oss/extensions/yesterday17.zenscript-0.2.4/out/server/services/zsDocumentContentChange.js:5:58)
(node:18684) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of null
    at Function.<anonymous> (/home/copygirl/.vscode-oss/extensions/yesterday17.zenscript-0.2.4/out/server/services/zsDocumentContentChange.js:37:64)
    at Generator.next (<anonymous>)
    at fulfilled (/home/copygirl/.vscode-oss/extensions/yesterday17.zenscript-0.2.4/out/server/services/zsDocumentContentChange.js:5:58)
(node:18684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:18684) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```
When typing, I get the same error as above:
```
[Error - 20.00.05] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'tokens' of undefined
  Code: -32603 
```
When hovering over any code, I get this:
```
[Error - 20.00.52] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'isInterpreted' of undefined
  Code: -32603
```

Not sure if relevant, but I am on Linux. My pack has 77 mods.

**Comment by Yesterday17** [comment]
Seems relevant to #28. How did you open the file, directly without folder(workspace) opened?

**Comment by copygirl** [comment]
I've opened the `.minecraft` folder of a MultiMC instance in VSCode.

**Comment by Krutoy242** [comment]
Have same issue. Sometimes errors jumps not instantly, but after some time. 
```[Error - 21:59:18] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Cannot read property 'oredictionary' of undefined
  Code: -32603 
```

**Comment by copygirl** [comment]
> Have same issue if i opened minecraft root folder as project folder.
> Issue wont happen if project folder is `.scripts`

(@Krutoy242 edited their message as I was writing my response.)

Ah, I see. I had tried opening the `scripts` folder directly before but had no luck there.

When looking at the readme, it says the following, and I decided that it meant the "minecraft folder mode" was the default (made sense to me, since I'd probably be editing both configs and scripts) and didn't think much of it.

> `zenscript.supportMinecraftFolderMode`: Whether your active folder is 'minecraft' like, which means that the extension detects `./scripts/.zsrc`, not `./.zsrc`.

Perhaps you could change the way the `.zsrc` file is detected: When a `.zs` file is opened or found, travel up the directory tree to find the corresponding `.zsrc`. Either until the root directory, or perhaps a maximum of, say, 5 folders. You may have a good reason for the way you have it set up, though.

**Comment by Yesterday17** [comment]
I published v0.2.5, could you please try this version?

@KittenRaee @copygirl @Krutoy242

**Comment by Krutoy242** [comment]
Still happens. Also, you can see keywords dont highlite propertly

<img src=https://i.imgur.com/T3UmwCg.png width=500>

Downgraded back to 1.41

**Comment by Yesterday17** [comment]
@Krutoy242 That's strange. Could you provide a (minimal) environment to reproduce this problem?

**Comment by Krutoy242** [comment]
> @Krutoy242 That's strange. Could you provide a (minimal) environment to reproduce this problem?

This would take many hours to test. Maybe i would try one day.
